### DISCUSSION TITLE
Can NGINX UI Run Against An Existing NGINX Container?

### DISCUSSION THREAD

**Discussion by jiriteach** [0xJacky/nginx-ui#1045] [Q&A] [answered]
Hi - If I have an NGINX container already running - is it possible to run NGINX UI in its own container talking to my existing NGINX container?

Thanks

**Comment by 0xJacky** [comment, marked as answer]
Hi @jiriteach, please check this documentation: https://nginxui.com/guide/config-nginx.html#container-control

**Reply by jiriteach** [reply]
Thanks - how would I specify this as a environment variable? So have NGINX-UI running as a container then wanting to manage another NGINX container.

**Reply by 0xJacky** [reply]
It shoud be NGINX_UI_NGINX_CONTAINER_NAME

**Reply by jiriteach** [reply]
Thanks - If I understand this correctly - 

Docker host = host1

container1 on host1 - nginx-ui
mapped via compose with environment variable NGINX_UI_NGINX_CONTAINER_NAME=app1

container2 on host1 - app1(with nginx)

Thats all thats needed? Tried that it threw some errors. Will have to dig in further.
But this is how it should work right?

**Reply by 0xJacky** [reply]
Well, Nginx UI can only control the container on the same machine.

**Reply by 0xJacky** [reply]
If you need to control a container on another host, you have to start the nginx-ui container on that host and add the environment on host1.

**Reply by jiriteach** [reply]
Ok - yes, these containers are on the same host - whoops sorry that was a typo, have corrected it - so its possible. Just wanted to check no further config was required. Could be permissions related then.

**Reply by 0xJacky** [reply]
Can you provide some logs or screenshots? thanks.

**Reply by jiriteach** [reply]
Sure. Both containers are on the same host.

NGINX UI container error - 

`2025-05-13 15:05:05	ERROR	/home/runner/work/nginx-ui/nginx-ui/internal/docker/stat_path.go:24	Failed to stat path error request returned 404 Not Found for API route and version http://%2Fvar%2Frun%2Fdocker.sock/v1.49/containers/temp-app1/archive?path=%2Frun%2Fnginx.pid, check if the server supports the requested API version`

NGINX UI - Dashboard NGINX page - 

<img width="229" alt="Screenshot 2025-05-13 at 15 06 08" src="https://github.com/user-attachments/assets/cbc8ed69-0cf5-4bd9-9207-98f3b94e2987" />

Compose - 

```
services:
    nginx-ui:
        stdin_open: true
        tty: true

        user: root
        
        container_name: nginx-ui
        restart: always
        environment:
            - TZ=Pacific/Auckland
            - NGINX_UI_NGINX_CONTAINER_NAME=temp-app1
        
        volumes:
            - '/home/administrator/Docker/nginx-ui/nginx:/etc/nginx'
            - '/home/administrator/Docker/nginx-ui/ui:/etc/nginx-ui'

            - '/home/administrator/Docker/nginx-ui/www:/var/www'
            
            - '/var/run/docker.sock:/var/run/docker.sock'
        
        ports:
            - 6002:80
            
            #- 8443:443
        
        image: 'uozi/nginx-ui:latest'
```
