### DISCUSSION TITLE
Setup NginxUI with a custom Nginx instance?

### DISCUSSION THREAD

**Discussion by Mqxx** [0xJacky/nginx-ui#1151] [Q&A]
Hey,
version 2.x is out and since I did not found a specific instruction to this #856 Issue I was hoping to get some help here.

As stated in the issue I would like to setup NginxUI with a custom Nginx docker instance. The default Nginx build that is shipped with NginxUI does not include the [community RTMP custom module](https://github.com/arut/nginx-rtmp-module) for Nginx. Therefore I want to use NginxUI just for the UI part and replace the Nginx that gets shipped with an other instance from a different container. I would like to use `docker compose` for that.

Can someone please give me a hint on how to setup NginxUI with an other Nginx instance ([this one for example](https://hub.docker.com/r/tiangolo/nginx-rtmp)) also running from the same `docker compose` file?

This is what I have so far:

https://nginxui.com/guide/config-nginx#container-control

```yml
services:
  nginx-service:
    container_name: 'nginx-service'
    image: 'tiangolo/nginx-rtmp:latest'
    # ...

  nginx-ui:
    container_name: 'nginx-ui'
    image: 'uozi/nginx-ui:latest'
    depends_on:
      - nginx-service

    environment:
      - NGINX_UI_NGINX_CONTAINER_NAME=nginx-service

    ports:
      - 8080:80
      - 8443:443

    volumes:
      - '/mnt/user/appdata/nginx:/etc/nginx'
      - '/mnt/user/appdata/nginx-ui:/etc/nginx-ui'
      - '/var/www:/var/www'
      - '/var/run/docker.sock:/var/run/docker.sock'

    stdin_open: true
    tty: true
    restart: unless-stopped
```

Problem with this is that I am unable to control the custom instance (for example restarting using the UI)

Also updating for example the config doesn't update it for the custom instance (I need to restart the custom instance manually every time using docker-compose)

Any help is appreciated, Thanks!
