### ISSUE TITLE
快速上手失败

### ISSUE THREAD

**Issue by kischn** [0xJacky/nginx-ui#1009]
Hi，尊敬的开发者们，我先后通过 docker-compose 和 windows exe 两种方式快速上手，均失败，还请帮忙分析一下是哪里操作不对。

## docker 方式
```yaml
services:
    nginx-ui:
        stdin_open: true
        tty: true
        container_name: nginx-ui
        restart: always
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - 'nginx_conf:/etc/nginx'
            - 'nginx_ui:/etc/nginx-ui'
            - 'www_data:/var/www'
        ports:
            - 8080:80
            - 8443:443
        image: 'uozi/nginx-ui:latest'
volumes:
  nginx_conf:
  nginx_ui:
  www_data:
```
使用上述指令启动后，8080 和 8443 均没有任何响应， curl 显示 empty response，进入容器后 curl 80 和 443 也没有任何响应，同时，tty 中无任何日志打印，隧放弃此方式，尝试使用更简单的方式试用一下。

## windows 绿色应用
在 github release 页面下载 v2.0.0-rc.6 中的  `nginx-ui-windows-64.tar.gz`，SHA256: 624b020b3d7151e90d6c9ff5714d94814024f4c430ad44c4887284b1abf470d3
解压后在旁边创建 `app.ini`，内容如下：
```ini
[server]
Host    = 0.0.0.0
Port    = 9999
HttpPort = 9999
RunMode = debug
```
使用命令 `.\nginx-ui.exe --config .\app.ini` 启动失败，说是 9000 端口被占用，但是我明明已经通过配置文件指定了其他端口。
并且关于端口的配置，我看官方文档里面是 `echo '[server]\nHttpPort = 9000' > app.ini` 这样的操作，但是代码示例里面是 Port ，我干脆两个都配置上，仍然无法将应用配置为监听 `9999` 端口。

<img width="1345" alt="Image" src="https://github.com/user-attachments/assets/4d1c8eea-e191-4be6-8b60-f81a3f19efce" />

还请各位开发者，有时间帮忙解答一下，感谢
