### ISSUE TITLE
Docker container only for UI

### ISSUE THREAD

**Issue by schmittyd** [0xJacky/nginx-ui#234]
**Is your feature request related to a problem? Please describe.**
I want to include just the UI in my Docker compose as I already have a SWAG container which has NGINX, Certbot and php.

**Describe the solution you'd like**
A separate container just for the UI.

**Comment by 0xJacky** [comment]
Hi, in nginx-ui, we need to execute some commands directly in the same environment with Nginx like to restart or reload it. If using a separate container just for the UI, we cannot control, test config files or get the running status of nginx.

**Comment by schmittyd** [comment]
Could you possibly add the GUI as a Docker mod to the NGINX and SWAG containers?
https://github.com/linuxserver/docker-mods

**Comment by leoperegrino** [comment]
bump. this would be useful for those who already are running nginx images and prefer not to switch. I use `linuxserver/nginx` which has few modifications such as configurations mountpoints (`/config`), users and groups. 

In case of a different image only for the UI, a form of communication of the UI and the separate nginx would be necessary. I think of shared volumes or network calls.

Shared volumes are ok if one only needs to read and write to configuration/log files, not execute commands. I don't know if nginx provides any type of RPCs or APIs for command execution, and even if it does that would pose a security risk.

Why having a shared mount between a nginx-ui UI container and a different nginx container is not enough? Maybe the only option is what @schmittyd sugested.

**Comment by jo-chemla** [comment]
Thanks for the implementation of managing nginx in another docker container in #977!

**Comment by Mqxx** [comment]
Are there any documentation on how to set this up? https://github.com/0xJacky/nginx-ui/discussions/1151

**Comment by 0xJacky** [comment]
> Are there any documentation on how to set this up? [#1151](https://github.com/0xJacky/nginx-ui/discussions/1151)

Please check this documentation: https://nginxui.com/guide/config-nginx.html#container-control

**Comment by Mqxx** [comment]
Thanks! I will try that 🙂

**Comment by Mqxx** [comment]
If I understand correctly I just need to specify an `env` variable in the docker-compose.yml called `NGINX_UI_NGINX_CONTAINER_NAME=` that points to the name of the container for the nginx instance.

**Comment by 0xJacky** [comment]
> If I understand correctly I just need to specify an `env` variable in the docker-compose.yml called `NGINX_UI_NGINX_CONTAINER_NAME=` that points to the name of the container for the nginx instance.

Yes, you're right.

**Comment by Mqxx** [comment]
So for example my docker-compose.yml would look like this?

```yml
services:
  nginx-service:
    container_name: 'nginx-service'
    image: 'tiangolo/nginx-rtmp:latest'
    volumes:
      - './data/nginx:/etc/nginx'

    ports:
      - '1935:1935'

    restart: unless-stopped
    # ...

  nginx-ui:
    container_name: 'nginx-ui'
    image: 'uozi/nginx-ui:latest'
    depends_on:
      - nginx-service

    environment:
      - NGINX_UI_NGINX_CONTAINER_NAME=nginx-service

    ports:
      - '8080:80'
      - '8443:443'

    volumes:
      - './data/nginx:/etc/nginx'
      - './data/nginx_ui:/etc/nginx-ui'
      - '/var/www:/var/www'
      - '/var/run/docker.sock:/var/run/docker.sock'

    stdin_open: true
    tty: true
    restart: unless-stopped
```
