### ISSUE TITLE
无法正常管理streams/Unable to manage streams properly

### ISSUE THREAD

**Issue by XZ1314XZ** [0xJacky/nginx-ui#240]
尝试手动去创建`/etc/nginx/streams-available`目录，但仍然报错。

系统：centos-8.5.2111
安装方式：docker-compose
docker-compose配置：
```yml
version: '3.8'
services:
    nginx-ui:
        container_name: nginx-ui
        restart: always
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - './appdata/nginx:/etc/nginx'
            - './appdata/nginx-ui:/etc/nginx-ui'
            - '/www/wwwroot:/var/www'
        ports:
            - 8080:80
            - 8443:443
        image: 'uozi/nginx-ui:latest'    
        networks:
            - nginx-net

networks:
  nginx-net:
    driver: bridge        
```
> 考虑到可能centos和教程示例的debian不一致，改用当前目录作为配置路径。
> 系统已安装宝塔面板，通过宝塔面板一键安装了nginx_v1.22.1。

---
I tried to manually create the `/etc/nginx/streams-available` directory, but I still encountered an error.

System: CentOS 8.5.2111
Installation method: Docker Compose
Docker Compose configuration:
```yml
version: '3.8'
services:
    nginx-ui:
        container_name: nginx-ui
        restart: always
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - './appdata/nginx:/etc/nginx'
            - './appdata/nginx-ui:/etc/nginx-ui'
            - '/www/wwwroot:/var/www'
        ports:
            - 8080:80
            - 8443:443
        image: 'uozi/nginx-ui:latest'    
        networks:
            - nginx-net

networks:
  nginx-net:
    driver: bridge        
```
> Considering that CentOS may differ from the Debian example in the tutorial, I used the current directory as the configuration path.
> The system has installed the Baota panel, and I used the Baota panel to install nginx_v1.22.1 with one click.

![Snipaste_2023-12-18_05-08-37](https://github.com/0xJacky/nginx-ui/assets/56338784/2e5c5ff4-db05-450f-8a7a-904f7f2a6b44)
