### ISSUE TITLE
Cannot enable PHP in a site

### ISSUE THREAD

**Issue by nikkilocke** [0xJacky/nginx-ui#253]
**Describe the bug**
I tried to enable PHP in a site, by adding the php template, but I get the error:
`open() "/etc/nginx/fastcgi.conf" failed (2: No such file or directory)` when saving the site

**To Reproduce**
Create a docker image with the following docker-compose:
```
version: '2.0'
services:
  nginx:
    image: uozi/nginx-ui
    restart: always
    environment:
      - TZ=Europe/London
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx-ui:/etc/nginx-ui
      - ./www:/var/www
```
Setup a site with an `index.php` file in the root, include the php template.
**Expected behavior**
The site can be saved.

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04.1
 - Server Arch:  x86_64
 - Nginx UI Version: How do I tell?
 - Your Browser: Chrome

**Additional context**
I assume that there needs to be a fast-cgi container running, but there is no point in having the PHP template if such a container is not included in the suggested docker-compose file.
