### ISSUE TITLE
添加站点时能否支持应用自己的基础模板？

### ISSUE THREAD

**Issue by jearton** [0xJacky/nginx-ui#296]
我在添加站点时，在基础信息部分有一大堆固定的东西要配置，每次手动添加指令，好麻烦。能否直接应用一套基础模板。比如我添加的指令有：

```nginx
#------------------------------security------------------------------#
add_header X-XSS-Protection         "1; mode=block" always;
add_header X-Content-Type-Options   "nosniff" always;
add_header Referrer-Policy          "no-referrer-when-downgrade" always;
add_header Content-Security-Policy  "default-src 'self' http: https: ws: wss: data: blob: 'unsafe-inline' 'unsafe-eval'; frame-ancestors 'self';" always;
add_header Permissions-Policy       "interest-cohort=()" always;
add_header X-Frame-Options          SAMEORIGIN;

# Access to .htaccess file is prohibited
location ~ /\.ht {
    deny all;
}

```

**Comment by jearton** [comment]
关于静态站点的文件管理，我绑了另一个镜像搭配去实现了，这里分享一下我的 docker compose 配置：

```yaml
version: '3.9'

services:
  nginx:
    image: uozi/nginx-ui:latest
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - filebrowser
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/docker/nginx/conf:/etc/nginx
      - ~/docker/nginx/ui:/etc/nginx-ui
      - ~/docker/nginx/www:/var/www
      - ~/docker/nginx/log:/var/log/nginx/local
    environment:
      - TZ=Asia/Shanghai
  filebrowser:
    image: filebrowser/filebrowser:v2-s6
    container_name: nginx-filebrowser
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ~/docker/nginx:/srv/nginx
      - ~/docker/nginx-filebrowser/database:/database
      - ~/docker/nginx-filebrowser/config:/config
    environment:
      - TZ=Asia/Shanghai
      - PUID=0
      - PGID=0

networks:
  backend:
   external:
     true
```

在站点列表里也添加了 filebrowser 的反向代理，然后只需要进入 www 目录，在线上传网站文件就可以了，www 下的一个目录对应一个网站。
![image](https://github.com/0xJacky/nginx-ui/assets/10370433/42ea881c-19da-45e3-be1b-aa15dcfa3b24)
