### ISSUE TITLE
docker version doesn't work

### ISSUE THREAD

**Issue by gromov-io** [0xJacky/nginx-ui#755]
**Describe the bug**
It's not working
 - Wildcard issue
 - Adding a site (Reverse Proxy)
 - Rebooting server via UI

**To Reproduce**
1. start the docker container as specified in the nginx-ui instructions
2. create a minimal virtual host
```
upstream uptime {
    server 91.222.238.242:3001;
}

server {
    listen 80;
	listen [::]:80;
    server_name uptime.grom-lab.ru;

    location / {
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
        proxy_pass http://uptime/;
    }
}
```
3. reload and restart server
4. go to uptime.grom-lab.ru - not work

**Expected behavior**
I go to uptime.grom-lab.ru and it works (opens the service that is specified in upstream).

**Screenshots**
-

**Info (please complete the following information):**
 - Server OS: Ubuntu 22.04
 - Server Arch: x86
 - Nginx UI Version: Version: 2.0.0-beta.39 (4)
 - Your Browser: Chrome, Firefox

**Additional context**
Thanks for the great product, it gave me hope that maybe I won't have to write configs on the server anymore. But unfortunately this great product doesn't work, or some non-standard manipulations are required.

**Comment by 0xJacky** [comment]
Hi @gromov-io, can you provide me the docker start command of the Nginx UI container?

**Comment by gromov-io** [comment]
> Привет @gromov-ioМожете ли вы предоставить мне команду запуска Docker для контейнера пользовательского интерфейса Nginx?

docker-compose.yml
```
  services:
    nginx-ui:
        stdin_open: true
        tty: true
        container_name: nginx-ui
        restart: always
        environment:
            - TZ=Europe/Moscow
        volumes:
            - './nginx:/etc/nginx'
            - './nginx-ui:/etc/nginx-ui'
            - './www:/var/www'
        ports:
            - 8080:80
            - 8443:443
        image: 'uozi/nginx-ui:latest'

```
