### ISSUE TITLE
希望可以自定义容器端口

### ISSUE THREAD

**Issue by zjjxwhh** [0xJacky/nginx-ui#824]
- System: 群晖，Linux 4.4.302
- Docker: Docker version 20.10.23, build 876964a

参考文档中的 docker 部署示例，通过以下 `docker-compose.yml` 在群晖的 docker 下以 bridge 网络模式部署 nginx-ui，`nginx-ui.conf` 的配置保持默认

```yaml
version: "3.3"
services:
  nginx-ui:
    image: uozi/nginx-ui:latest
    container_name: nginx-ui
    volumes:
      - /volume1/docker/nginx-ui/nginx:/etc/nginx
      - /volume1/docker/nginx-ui/nginx-ui:/etc/nginx-ui
    environment:
      - TZ=Asia/Shanghai
      - NGINX_UI_SERVER_RUN_MODE=release
      - NGINX_UI_LOGROTATE_ENABLED=true
      - NGINX_UI_NGINX_ACCESS_LOG_PATH=/var/log/nginx/access.log
      - NGINX_UI_NGINX_ERROR_LOG_PATH=/var/log/nginx/error.log
      - NGINX_UI_NGINX_LOG_DIR_WHITE_LIST=/var/log/nginx
      - NGINX_UI_TERMINAL_START_CMD=bash
    ports:
      - 11080:80
      - 11443:443
    network_mode: bridge
    stdin_open: true
    tty: true
    restart: always
```

使用中发现，nginx 无法获得访问者的真实 IP，nginx 的访问日志中打印的都是 docker bridge 网络网关的 IP（172.17.0.1）

```
# /var/log/nginx/access.log
#
#     log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
#                       '$status $body_bytes_sent "$http_referer" '
#                       '"$http_user_agent" "$http_x_forwarded_for"';

172.17.0.1 - - [19/Jan/2025:18:19:30 +0800] "GET /api/site_categories HTTP/1.1" 200 83 "http://192.168.9.50:11080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36" "-"
172.17.0.1 - - [19/Jan/2025:18:19:30 +0800] "POST /api/nginx/test HTTP/1.1" 200 159 "http://192.168.9.50:11080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36" "-"
172.17.0.1 - - [19/Jan/2025:18:19:30 +0800] "GET /api/sites?site_category_id=0&order=desc&sort_by=&trash=false&page=1&page_size=20 HTTP/1.1" 200 5691 "http://192.168.9.50:11080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36" "-"
```

经过一番搜索之后发现，这似乎是由于采用 **bridge** 网络模式部署导致，如果使用 **host** 网络模式部署就可以避免这个问题。但是由于群晖的 80 和 443 端口已经被占用，无法以 host 网络模式部署😅
因此，是否有可能自定义容器监听的 80 及 443 端口（比如增加两个环境变量 `-e NGINX_UI_HTTP_PORT=11080 -e NGINX_UI_HTTPS_PORT=11443`），这样可以在指定 `--network host` 时更灵活的部署容器
或者有其他变通的方法解决上述真实 IP 无法获取的问题，也麻烦指导，感谢！
